// Code generated by go-swagger; DO NOT EDIT.

package update

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateOKCode is the HTTP code returned for type UpdateOK
const UpdateOKCode int = 200

/*UpdateOK returns a hash

swagger:response updateOK
*/
type UpdateOK struct {

	/*did create hash
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateOK creates UpdateOK with default headers values
func NewUpdateOK() *UpdateOK {

	return &UpdateOK{}
}

// WithPayload adds the payload to the update o k response
func (o *UpdateOK) WithPayload(payload string) *UpdateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update o k response
func (o *UpdateOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
