---
swagger: '2.0'
info:
  description: IoTex Driver
  version: "1.0.0"
  title: IoTex Driver
  contact:
    email: xx@x.com
paths:
  /identifiers/{identifier}:
    get:
      summary: Resolve a DID or other identifier.
      operationId: resolve
      parameters:
        - in: path
          required: true
          name: identifier
          type: string
          description: A DID or other identifier to be resolved.
      responses:
        '200':
          schema:
            ref: '#/components/schemas/ResolutionResult'
        '400':
          description: invalid input!
        '500':
          description: error!
components:
  schemas:
    ResolutionResult:
      description: The DID resolution result.
      type: object
      additionalProperties: false
      properties:
        didDocument:
          type: object
        resolverMetadata:
          type: object
        methodMetadata:
          type: object