---
swagger: '2.0'
info:
  description: IoTex Driver
  version: "1.0.0"
  title: IoTex Driver
  contact:
    email: xx@x.com
paths:
  /identifiers/{identifier}:
    get:
      summary: Resolve a DID or other identifier.
      operationId: resolve
      parameters:
        - in: path
          required: true
          name: identifier
          schema:
            type: string
          description: A DID or other identifier to be resolved.
        - in: header
          required: false
          name: Accept
          schema:
            type: string
          description: The requested MIME type of the DID document or DID resolution result.
          examples:
            application/did+json:
              value: application/json
              description: MIME type of a DID document (JSON representation)
            application/did+ld+json:
              value: application/did+ld+json
              description: MIME type of a DID document (JSON-LD representation)
            application/ld+json;profile=\"https://w3c-ccg.github.io/did-resolution/\":
              value: application/ld+json;profile=\"https://w3c-ccg.github.io/did-resolution/\"
              description: MIME type of a DID resolution result
      responses:
        '200':
          description: successfully resolved!
          content:
            application/did+json:
              schema:
                type: object
                description: The DID document (JSON representation).
            application/did+ld+json:
              schema:
                type: object
                description: The DID document (JSON-LD representation).
            application/ld+json;profile=\"https://w3c-ccg.github.io/did-resolution/\":
              schema:
                $ref: '#/components/schemas/ResolutionResult'
        '400':
          description: invalid input!
        '500':
          description: error!
components:
  schemas:
    ResolutionResult:
      description: The DID resolution result.
      type: object
      additionalProperties: false
      properties:
        didDocument:
          type: object
        resolverMetadata:
          type: object
        methodMetadata:
          type: object