---
swagger: '2.0'
info:
  version: 1.0.0
  title: Did
paths:
  /did:
    post:
      produces:
        - text/plain
      parameters:
        - in: body
          name: body
          description: Create object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Create'
      operationId: create
      responses:
        200:
          description: returns a hash
          schema:
              type: string
              description: did create hash
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

definitions:
  Create:
    type: object
      required:
        - id
        - hash
        - uri
    properties:
      id:
        type: string
        format: string
      hash:
        type: string
        format: string
        minLength: 64
      uri:
        type: string
        format: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
      fields:
        type: string
  principal:
    type: string