---
swagger: '2.0'
info:
  version: 1.0.0
  title: Did
paths:
  /did:
    post:
      tags: ["create"]
      operationId: create
      summary: Create a new customer to track
      parameters:
        - name: info
          in: body
          schema:
            $ref: "#/definitions/Create"
      responses:
        200:
          description: returns a hash
          schema:
              type: string
              description: did create hash
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

definitions:
  Create:
    type: object
    required:
      - id
      - hash
      - uri
    properties:
      id:
        type: string
        format: string
      hash:
        type: string
        format: string
        minLength: 64
      uri:
        type: string
        format: string