---
swagger: '2.0'
info:
  version: 1.0.0
  title: Did
paths:
  /did:
    post:
      tags: ["update"]
      operationId: update
      summary: include createDID deleteDID updateHash updateURI
      parameters:
        - name: info
          in: body
          schema:
            $ref: "#/definitions/jsonrpc"
      responses:
        200:
          description: returns a hash
          schema:
              type: string
              description: did create hash
    get:
      tags: ["get"]
      operationId: get
      summary: include getHash getURI
      parameters:
        - name: info
          in: body
          schema:
            $ref: "#/definitions/jsonrpc"
      responses:
        200:
          description: returns jsonrpc
          schema:
            type: string
            description: standard jsonrpc
definitions:
  jsonrpc:
    type: object
    required:
      - jsonbody
    properties:
      jsonbody:
        type: string
        format: string