---
swagger: '2.0'
chainpoint: "api.testnet.iotex.one:443"
contract: "io1zgs5gqjl679qlj4gqqpa9t329r8f5gr8xc9lr0"
info:
  version: 1.0.0
  title: Did
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /did:
    post:
      tags: ["update"]
      operationId: update
      summary: include method createDID deleteDID updateHash updateURI
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/json"
      responses:
        200:
          description: returns a hash
          schema:
              type: string
              description: did create hash
    get:
      tags: ["get"]
      operationId: get
      summary: include method getHash getURI
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/json"
      responses:
        200:
          description: returns jsonrpc
          schema:
            type: string
            description: standard jsonrpc
definitions:
  json:
    type: object
    required:
      - jsonrpc
      - id
      - method
    properties:
      jsonrpc:
        type: string
        format: string
      id:
        type: string
        format: string
      method:
        type: string
        format: string
      params:
        type: array
        items:
          type: string
          format: string