---
swagger: '2.0'
info:
  version: 1.0.0
  title: Did
paths:
  /did:
    post:
      produces:
        - text/plain
      parameters:
        - name: id
          required: true
          type: string
          in: query
        - name: hash
          required: true
          type: string
          in: query
        - name: uri
          required: true
          type: string
          in: query
      operationId: create
      responses:
        200:
          description: returns a hash
          schema:
              type: string
              description: did create hash
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
      fields:
        type: string