---
swagger: '2.0'
info:
  version: 1.0.0
  title: Did restful Server
paths:
  /did:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to empty if not given
      operationId: getDid
      responses:
        200:
          description: returns a did
          schema:
              type: string
              description: contains the actual greeting as plain text
