// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDidOKCode is the HTTP code returned for type GetDidOK
const GetDidOKCode int = 200

/*GetDidOK returns a did

swagger:response getDidOK
*/
type GetDidOK struct {

	/*contains the actual greeting as plain text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDidOK creates GetDidOK with default headers values
func NewGetDidOK() *GetDidOK {

	return &GetDidOK{}
}

// WithPayload adds the payload to the get did o k response
func (o *GetDidOK) WithPayload(payload string) *GetDidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get did o k response
func (o *GetDidOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
