// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDidHandlerFunc turns a function with the right signature into a get did handler
type GetDidHandlerFunc func(GetDidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDidHandlerFunc) Handle(params GetDidParams) middleware.Responder {
	return fn(params)
}

// GetDidHandler interface for that can handle valid get did params
type GetDidHandler interface {
	Handle(GetDidParams) middleware.Responder
}

// NewGetDid creates a new http.Handler for the get did operation
func NewGetDid(ctx *middleware.Context, handler GetDidHandler) *GetDid {
	return &GetDid{Context: ctx, Handler: handler}
}

/*GetDid swagger:route GET /did getDid

GetDid get did API

*/
type GetDid struct {
	Context *middleware.Context
	Handler GetDidHandler
}

func (o *GetDid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDidParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
