// Code generated by go-swagger; DO NOT EDIT.

// Package restapi IoTex Driver
//
//  IoTex Driver
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  Contact: <xx@x.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
