// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Did
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//    - text/plain
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
