// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Did",
    "version": "1.0.0"
  },
  "paths": {
    "/did": {
      "post": {
        "produces": [
          "text/plain"
        ],
        "operationId": "create",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "hash",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "uri",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns a hash",
            "schema": {
              "description": "did create hash",
              "type": "string"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Did",
    "version": "1.0.0"
  },
  "paths": {
    "/did": {
      "post": {
        "produces": [
          "text/plain"
        ],
        "operationId": "create",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "hash",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "uri",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns a hash",
            "schema": {
              "description": "did create hash",
              "type": "string"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
