// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Did",
    "version": "1.0.0"
  },
  "paths": {
    "/did": {
      "get": {
        "tags": [
          "get"
        ],
        "summary": "include getHash getURI",
        "operationId": "get",
        "parameters": [
          {
            "name": "info",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/jsonrpc"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns jsonrpc",
            "schema": {
              "description": "standard jsonrpc",
              "type": "string"
            }
          }
        }
      },
      "post": {
        "tags": [
          "update"
        ],
        "summary": "include createDID deleteDID updateHash updateURI",
        "operationId": "update",
        "parameters": [
          {
            "name": "info",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/jsonrpc"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a hash",
            "schema": {
              "description": "did create hash",
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "jsonrpc": {
      "type": "object",
      "required": [
        "jsonbody"
      ],
      "properties": {
        "jsonbody": {
          "type": "string",
          "format": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Did",
    "version": "1.0.0"
  },
  "paths": {
    "/did": {
      "get": {
        "tags": [
          "get"
        ],
        "summary": "include getHash getURI",
        "operationId": "get",
        "parameters": [
          {
            "name": "info",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/jsonrpc"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns jsonrpc",
            "schema": {
              "description": "standard jsonrpc",
              "type": "string"
            }
          }
        }
      },
      "post": {
        "tags": [
          "update"
        ],
        "summary": "include createDID deleteDID updateHash updateURI",
        "operationId": "update",
        "parameters": [
          {
            "name": "info",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/jsonrpc"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a hash",
            "schema": {
              "description": "did create hash",
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "jsonrpc": {
      "type": "object",
      "required": [
        "jsonbody"
      ],
      "properties": {
        "jsonbody": {
          "type": "string",
          "format": "string"
        }
      }
    }
  }
}`))
}
