// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Did",
    "version": "1.0.0"
  },
  "paths": {
    "/did": {
      "get": {
        "tags": [
          "get"
        ],
        "summary": "include method getHash getURI",
        "operationId": "get",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/json"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns jsonrpc",
            "schema": {
              "description": "standard jsonrpc",
              "type": "string"
            }
          }
        }
      },
      "post": {
        "tags": [
          "update"
        ],
        "summary": "include method createDID deleteDID updateHash updateURI",
        "operationId": "update",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/json"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a hash",
            "schema": {
              "description": "did create hash",
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "json": {
      "type": "object",
      "required": [
        "jsonrpc",
        "id",
        "method"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "string"
        },
        "jsonrpc": {
          "type": "string",
          "format": "string"
        },
        "method": {
          "type": "string",
          "format": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "string"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Did",
    "version": "1.0.0"
  },
  "paths": {
    "/did": {
      "get": {
        "tags": [
          "get"
        ],
        "summary": "include method getHash getURI",
        "operationId": "get",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/json"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns jsonrpc",
            "schema": {
              "description": "standard jsonrpc",
              "type": "string"
            }
          }
        }
      },
      "post": {
        "tags": [
          "update"
        ],
        "summary": "include method createDID deleteDID updateHash updateURI",
        "operationId": "update",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/json"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a hash",
            "schema": {
              "description": "did create hash",
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "json": {
      "type": "object",
      "required": [
        "jsonrpc",
        "id",
        "method"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "string"
        },
        "jsonrpc": {
          "type": "string",
          "format": "string"
        },
        "method": {
          "type": "string",
          "format": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "string"
          }
        }
      }
    }
  }
}`))
}
