// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Jsonrpc jsonrpc
//
// swagger:model jsonrpc
type Jsonrpc struct {

	// jsonbody
	// Required: true
	Jsonbody *string `json:"jsonbody"`
}

// Validate validates this jsonrpc
func (m *Jsonrpc) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJsonbody(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Jsonrpc) validateJsonbody(formats strfmt.Registry) error {

	if err := validate.Required("jsonbody", "body", m.Jsonbody); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Jsonrpc) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Jsonrpc) UnmarshalBinary(b []byte) error {
	var res Jsonrpc
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
